# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='描述'),
        ),
    ]
